# Site
name: "Rough Drafts"
description: "Rough Drafts of my thoughts on the world"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "mpfrizzell@gmail.com"
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  michael:
    name: Michael Frizzell
    site: https://michaelfrizzell.com
    avatar: https://pbs.twimg.com/profile_images/1363993711621799936/wGyOctYO_400x400.png
    bio: "Hi, I am Michael Frizzell, a writer, photographer, and healthcare worker in the Missouri Ozarks."
    email: mpfrizzell@gmail.com
    twitter: https://twitter.com/frizz

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: michael
      avatar: https://pbs.twimg.com/profile_images/1363993711621799936/wGyOctYO_400x400.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
